import fs from 'fs';
import path from 'path';

export class FileWriter {
  private static ensureDir(filePath: string) {
    const dir = path.dirname(filePath);
    if (!fs.existsSync(dir)) {
      fs.mkdirSync(dir, { recursive: true });
    }
  }

  /**
   * Writes or Appends to a generated file.
   * @param append - If true, adds to existing content. If false (default), overwrites.
   */
  static writeGeneratedFile(
    filePath: string,
    content: string,
    scriptName: string,
    append = false,
  ) {
    this.ensureDir(filePath);

    const banner = `// AUTO-GENERATED FILE — do not edit manually\n// Generated by scripts/${scriptName}\n\n`;
    const exists = fs.existsSync(filePath);

    // Only add banner if we are overwriting or the file doesn't exist yet
    let finalContent = content;
    if (!exists || !append) {
      finalContent = content.trim().startsWith('//')
        ? content
        : banner + content;
    } else {
      // If appending, just add a separator
      finalContent = `\n\n--- APPENDED: ${new Date().toISOString()} ---\n${content}`;
    }

    if (append && exists) {
      fs.appendFileSync(filePath, finalContent);
      console.log(
        `   -> Appended to: ${path.relative(process.cwd(), filePath)}`,
      );
    } else {
      fs.writeFileSync(filePath, finalContent);
      console.log(`   -> Generated: ${path.relative(process.cwd(), filePath)}`);
    }
  }

  /**
   * Creates a brand new unique file in the folder (e.g., for audit history).
   * Result: audit-report-1704067200.md
   */
  static createNewAuditFile(
    folderPath: string,
    baseName: string,
    extension: string,
    content: string,
  ) {
    if (!fs.existsSync(folderPath)) {
      fs.mkdirSync(folderPath, { recursive: true });
    }

    // Use a timestamp or UUID to ensure it's a "new" file
    const timestamp = Date.now();
    const fileName = `${baseName}-${timestamp}.${extension}`;
    const fullPath = path.join(folderPath, fileName);

    fs.writeFileSync(fullPath, content);
    console.log(
      `   -> Created New Record: ${path.relative(process.cwd(), fullPath)}`,
    );
    return fullPath;
  }

  static writeJson(filePath: string, data: unknown) {
    this.ensureDir(filePath);
    fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
    console.log(`   -> Data Saved: ${path.relative(process.cwd(), filePath)}`);
  }
}
